export type ProductPictograms = {
  images?: { src: string; label: string }[];
};

export type Product = {
  id: string;
  name: string;
  category: 'food-safe' | 'chemical' | 'disposable' | 'industrial' | 'household' | 'seamless';
  categoryLabel: string;
  img: string;
  material: 'natural' | 'nitrile' | 'nbr';
  length: 'short' | 'medium' | 'long' | 'extra-long' | 'disposable';
  tags: string[];
  features: string[];
  specs: Record<string, string>;
  desc: string;
  color: string;
  env: ('heavy-industry' | 'assembly-general' | 'lab-precision' | 'food-kitchen' | 'cleaning-household')[];
  props: ('chemical' | 'water-oil' | 'cut' | 'abrasion' | 'disposable' | 'precision')[];
  datasheet?: string;
  video?: string;
  pictograms?: ProductPictograms;
};

export const PRODUCTS: Product[] = [
  // ── ÖNCELİKLİ ÜRÜNLER ────────────────────────────────────────
  {
    id: 'nitrofl-330-15sd',
    name: 'NitroFL™ 330-15SD',
    category: 'chemical', categoryLabel: 'Kimyasal',
    img: '/products/chemical/nitrofl-330-15sd.png',
    material: 'nitrile', length: 'medium',
    tags: ['Kimyasal Direnç', 'Kaymaz Tutuş', 'Kesme Dayanımı'],
    features: ['Tam Daldırma', 'Pürüzlü Yüzey', 'Uzun Pazu'],
    specs: { 'Uzunluk': '380mm', 'Kalınlık': '0.50mm', 'Renk': 'Yeşil', 'Astar': 'Pamuk flok' },
    desc: 'Zorlu kimyasal ortamlar için tasarlanmış nitril kauçuk eldiven. Kaymaz yüzeyi ve uzun pazu tasarımıyla kimyasal madde kullanılan sektörlerde üstün koruma sağlar.',
    color: '#003885',
    env: ['heavy-industry', 'lab-precision'],
    props: ['chemical', 'water-oil', 'cut', 'abrasion'],
    datasheet: '/documents/nitrofl-330-15sd.pdf',
    pictograms: {
      images: [
        { src: '/pictograms/ce-cat3.png',           label: 'CE KKD Kategori III' },
        { src: '/pictograms/jkot.png',              label: 'JKOT Kimyasalları' },
        { src: '/pictograms/gidaya-uygun.png',      label: 'Gıdaya Uygun' },
        { src: '/pictograms/en-iso-21420.png',      label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'naturafl-300-15bf',
    name: 'NaturaFL™ 300-15BF',
    category: 'food-safe', categoryLabel: 'Gıdaya Uygun',
    img: '/products/industrial/naturafl-300-15bf.png',
    material: 'natural', length: 'medium',
    tags: ['Kobalt Mavi', 'Gıda Onaylı', 'Flok Astarlı'],
    features: ['Doğal Kauçuk', 'Gıda Temasına Uygun', 'Konforlu Astar', 'Kaymaz Tutus'],
    specs: { 'Uzunluk': '380mm', 'Kalınlık': '0.50mm', 'Renk': 'Kobalt Mavi', 'Astar': 'Pamuk flok' },
    desc: 'Gıda işleme ve konserve sektörü için onaylanmış kobalt mavi doğal lateks eldiven. Pamuk flok astarı ve balık pulu tutuş deseni ile uzun vardiyalarda yüksek konfor sağlar.',
    color: '#1255a8',
    env: ['food-kitchen', 'assembly-general'],
    props: ['water-oil'],
    datasheet: '/documents/naturafl-300-15bf.pdf',
    video: '/videos/naturafl-300-15bf.mp4',
    pictograms: {
      images: [
        { src: '/pictograms/ce-2777.png',      label: 'CE 2777 KKD Kategori I' },
        { src: '/pictograms/en-iso-374.png',   label: 'EN ISO 374-1 Kimyasal' },
        { src: '/pictograms/jkot.png',         label: 'JKOT Kimyasalları' },
        { src: '/pictograms/gidaya-uygun.png', label: 'Gıdaya Uygun' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  // ── TEK KULLANIMLIK ───────────────────────────────────────────
  {
    id: 'lalan-2-8',
    name: 'Lalan LITE28™',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-2.8.png',
    material: 'nitrile', length: 'disposable',
    tags: ['2.8g', 'Ekonomik', 'Pudrasız'],
    features: ['Pudrasız', 'Lateks İçermez', 'Ambidextrous'],
    specs: { 'Kalınlık': '0.10mm', 'Ağırlık': '2.8g', 'Renk': 'Mavi', 'Paket': '100 adet/kutu' },
    desc: 'Hafif ve ekonomik tek kullanımlık nitril eldiven. Gıda, temizlik ve hafif koruma gerektiren işler için uygundur.',
    color: '#003885',
    env: ['food-kitchen', 'cleaning-household'],
    props: ['disposable'],
    datasheet: '/documents/lalan-2-8.pdf',
  },
  {
    id: 'lalan-lite-3-2',
    name: 'Lalan Lite™ 3.2',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-lite.png',
    material: 'nitrile', length: 'disposable',
    tags: ['Pudrasız', 'Tek Kullanımlık', 'Yüksek Hassasiyet'],
    features: ['Pudrasız', 'Lateks İçermez', 'Hafif Yapı', 'Hijyenik'],
    specs: { 'Kalınlık': '0.10mm', 'Ağırlık': '3.2g', 'Renk': 'Mavi/Gri', 'Sertifika': 'EN 455' },
    desc: 'Ultra ince nitril yapısıyla hassas işlemler ve tek kullanımlık hijyen gerektiren ortamlar için ideal. Pudrasız ve lateks içermez.',
    color: '#003885',
    env: ['lab-precision'],
    props: ['disposable', 'precision'],
    datasheet: '/documents/lalan-lite-3-2.pdf',
  },
  {
    id: 'lalan-strong-f',
    name: 'Lalan Strong F™',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-strong-f.png',
    material: 'nitrile', length: 'disposable',
    tags: ['Güçlü', '5g', 'Dayanıklı'],
    features: ['Güçlendirilmiş Nitril', 'Parmak Ucu Pürüzlü', 'Ağır İş'],
    specs: { 'Kalınlık': '0.12mm', 'Ağırlık': '5.0g', 'Renk': 'Mavi', 'Paket': '100 adet/kutu' },
    desc: 'Standart tek kullanımlık eldivenlerden daha kalın nitril duvarıyla güçlü koruma. Temizlik, sanayi ve kimyasal temaslar için uygundur.',
    color: '#3a73bc',
    env: ['cleaning-household', 'assembly-general', 'heavy-industry'],
    props: ['disposable', 'chemical', 'water-oil'],
    datasheet: '/documents/lalan-strong-f.pdf',
  },
  {
    id: 'lalan-strong-x',
    name: 'Lalan Strong X™',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-strong-x.png',
    material: 'nitrile', length: 'disposable',
    tags: ['Extra Güçlü', '6.3g', 'Ağır Hizmet'],
    features: ['Extra Kalın Nitril', 'Pürüzlü Yüzey', 'Uzatılmış Bilek'],
    specs: { 'Kalınlık': '0.15mm', 'Ağırlık': '6.3g', 'Renk': 'Mavi/Siyah', 'Paket': '50 adet/kutu' },
    desc: 'Tek kullanımlık kategorinin en güçlü modeli. Ağır temizlik, kimyasal ve endüstriyel uygulamalar için sektörün en yüksek koruma seviyesi.',
    color: '#3a73bc',
    env: ['heavy-industry', 'assembly-general'],
    props: ['disposable', 'chemical', 'water-oil'],
    datasheet: '/documents/lalan-strong-x.pdf',
  },
  {
    id: 'lalan-strong-x-esd',
    name: 'Lalan Strong X ESD™',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-strong-x-esd.png',
    material: 'nitrile', length: 'disposable',
    tags: ['ESD', 'Anti-statik', 'Elektronik'],
    features: ['ESD Korumalı', 'Anti-statik', 'Elektronik Sektör', 'Extra Kalın'],
    specs: { 'Kalınlık': '0.15mm', 'ESD': 'IEC 61340-5-1', 'Renk': 'Siyah', 'Paket': '50 adet/kutu' },
    desc: 'ESD (Elektrostatik Deşarj) korumalı formülasyonuyla elektronik üretim ve hassas bileşen montajı için geliştirilmiş özel nitril eldiven.',
    color: '#222',
    env: ['lab-precision', 'assembly-general'],
    props: ['disposable', 'precision'],
    datasheet: '/documents/lalan-strong-x-esd.pdf',
  },
  // ── KİMYASAL ────────────────────────────────────────────────
  {
    id: 'nitrofl-330-18sf',
    name: 'NitroFL™ 330-18SF',
    category: 'chemical', categoryLabel: 'Kimyasal',
    img: '/products/chemical/nitrofl-330-18sf.png',
    material: 'nitrile', length: 'long',
    tags: ['Kimyasal Direnç', 'Uzun Pazu', 'Süet Astarlı'],
    features: ['Süet Astarlı', 'Uzatılmış Pazu', 'Anti-slip', 'CE Kat. III'],
    specs: { 'Uzunluk': '460mm', 'Kalınlık': '0.55mm', 'Renk': 'Mavi', 'Astar': 'Flok' },
    desc: 'NitroFL serisinin uzun pazu versiyonu. 460mm uzunluğuyla kolları da koruyan nitril eldiven; kimyasal madde kullanımı, tarım ve atık yönetimi uygulamaları için idealdir.',
    color: '#003885',
    env: ['heavy-industry', 'lab-precision'],
    props: ['chemical', 'water-oil'],
  },
  {
    id: 'duonpfl-330-24sd',
    name: 'DUONPFL™ 330-24SD',
    category: 'chemical', categoryLabel: 'Kimyasal',
    img: '/products/chemical/duonpfl-330-24sd.png',
    material: 'nitrile', length: 'extra-long',
    tags: ['Çift Kaplama', 'Ekstra Uzun', 'Kimyasal Koruma'],
    features: ['Çift Daldırma Teknolojisi', 'Ekstra Uzun Pazu', 'Ağır Hizmet', 'CE Kat. III'],
    specs: { 'Uzunluk': '600mm', 'Kalınlık': '0.65mm', 'Renk': 'Yeşil/Sarı', 'Astar': 'Pamuk' },
    desc: 'Çift kaplama teknolojisiyle en zorlu kimyasal ortamlar için geliştirilmiş 60cm uzunluğunda nitril eldiven. İnşaat, kimya ve temizlik sektörlerine yönelik üst düzey kimyasal koruma sağlar.',
    color: '#004f11',
    env: ['heavy-industry'],
    props: ['chemical', 'water-oil'],
  },
  // ── ENDÜSTRİYEL ───────────────────────────────────────────────
  {
    id: 'naturafl-300-11bf',
    name: 'NaturaFL™ 300-11BF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturafl-300-11bf.png',
    material: 'natural', length: 'short',
    tags: ['Doğal Lateks', 'Flok Astarlı', 'Genel Endüstri'],
    features: ['Doğal Kauçuk', 'Flok Astar', 'Kaymaz Parmak', 'Balık Pulu Tutuş'],
    specs: { 'Uzunluk': '300mm', 'Kalınlık': '0.50mm', 'Renk': 'Sarı', 'Astar': 'Pamuk flok' },
    desc: 'Doğal lateksin esnekliğini endüstriyel dayanıklılıkla buluşturan flok astarlı genel endüstri eldiveni. Tarım, genel üretim ve konserve sektörlerine uygundur.',
    color: '#8c6500',
    env: ['heavy-industry', 'assembly-general', 'food-kitchen'],
    props: ['water-oil'],
  },
  {
    id: 'naturafl-300-22sf',
    name: 'NaturaFL™ 300-22SF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturafl-300-22sf.png',
    material: 'natural', length: 'long',
    tags: ['Doğal Lateks', 'Süet Astarlı', 'Uzun'],
    features: ['Süet Astar', 'Gıda Uyumlu', 'Uzun Pazu', 'Konfor'],
    specs: { 'Uzunluk': '560mm', 'Kalınlık': '0.55mm', 'Renk': 'Sarı', 'Astar': 'Pamuk süet' },
    desc: 'Süet astarlı ve gıda sektörüne uygun uzun pazu doğal lateks endüstriyel eldiven. Balık işleme, konserve ve genel gıda üretimi için tercih edilir.',
    color: '#8c6500',
    env: ['food-kitchen', 'assembly-general', 'heavy-industry'],
    props: ['water-oil'],
  },
  {
    id: 'naturafl-330-28bf',
    name: 'NaturaFL™ 330-28BF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturafl-330-28bf.png',
    material: 'natural', length: 'extra-long',
    tags: ['Doğal Lateks', 'Ekstra Uzun', 'Ağır Hizmet'],
    features: ['Ekstra Uzun Pazu', 'Kalın Kaplama', 'Güçlendirilmiş Yaka'],
    specs: { 'Uzunluk': '710mm', 'Kalınlık': '0.60mm', 'Renk': 'Sarı', 'Astar': 'Pamuk flok' },
    desc: 'Kimya ve petrokimya sektörü için geliştirilmiş ekstra uzun pazu doğal lateks endüstriyel eldiven. 710mm uzunluğuyla üst kola kadar tam koruma sağlar.',
    color: '#8c6500',
    env: ['heavy-industry'],
    props: ['chemical', 'water-oil'],
  },
  {
    id: 'naturahd-330-32b',
    name: 'NaturaHD™ 330-32B',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturahd-330-32b.png',
    material: 'natural', length: 'extra-long',
    tags: ['Ağır Hizmet', 'Ekstra Uzun', 'Yüksek Kalınlık'],
    features: ['HD Formülasyon', 'Ekstra Kalın', 'Uzun Pazu', 'Yüksek Dayanıklılık'],
    specs: { 'Uzunluk': '810mm', 'Kalınlık': '0.80mm', 'Renk': 'Sarı/Kahve', 'Astar': 'Pamuk' },
    desc: 'En ağır sanayi uygulamaları için geliştirilmiş yüksek yoğunluklu (HD) doğal lateks eldiven. 810mm uzunluk ve 0.80mm kalınlıkla petrokimya, maden ve ağır metal endüstrilerine uygundur.',
    color: '#6b4c00',
    env: ['heavy-industry'],
    props: ['chemical', 'water-oil', 'cut', 'abrasion'],
  },
  {
    id: 'naturaul-300-12bf',
    name: 'NaturaUL™ 300-12BF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturaul-300-12bf.png',
    material: 'natural', length: 'short',
    tags: ['Ultra İnce', 'Hassas İş', 'Gıda Onaylı'],
    features: ['Ultra İnce (UL)', 'Hassas Tutuş', 'Gıda Onaylı', 'Klorlanmış Finish', 'CE Kat. III'],
    specs: { 'Uzunluk': '305mm', 'Kalınlık': '0.25mm', 'Renk': 'Mavi/Krem', 'Astar': 'Yok (klorlanmış)' },
    desc: 'Ultra ince lateks duvarıyla maksimum hassasiyet sağlayan endüstriyel eldiven. Elektronik montaj, laboratuvar ve gıda işleme alanlarında yüksek dokunma duyarlılığı sunar.',
    color: '#c87c00',
    env: ['lab-precision', 'food-kitchen', 'assembly-general'],
    props: ['precision'],
  },
  {
    id: 'naturaul-300-15bf',
    name: 'NaturaUL™ 300-15BF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturaul-300-15bf.png',
    material: 'natural', length: 'medium',
    tags: ['Ultra İnce', 'Uzun Pazu', 'Gıda Onaylı'],
    features: ['Ultra İnce (UL)', 'Orta Boy Pazu', 'Hassas Dokunuş', 'Gıda Onaylı', 'CE Kat. III'],
    specs: { 'Uzunluk': '380mm', 'Kalınlık': '0.25mm', 'Renk': 'Mavi', 'Astar': 'Yok' },
    desc: 'Ultra ince lateks yapısıyla maksimum hassasiyet, orta boy pazusuyla ek koruma sunan endüstriyel eldiven. Konserve, gıda işleme, laboratuvar ve kimyasal kullanım alanlarına uygundur.',
    color: '#c87c00',
    env: ['lab-precision', 'food-kitchen', 'assembly-general'],
    props: ['precision', 'chemical'],
  },
  {
    id: 'nbrfl-300-11bf',
    name: 'NBRFL™ 300-11BF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/nbrfl-300-11bf.png',
    material: 'nbr', length: 'short',
    tags: ['NBR', 'Yağ Direnci', 'Flok Astarlı'],
    features: ['NBR Kauçuk', 'Yağ & Yakıt Direnci', 'Flok Astar', 'Balık Pulu Tutuş'],
    specs: { 'Uzunluk': '300mm', 'Kalınlık': '0.28mm', 'Renk': 'Siyah', 'Astar': 'Pamuk flok' },
    desc: 'NBR (Nitril-Bütadien Kauçuk) yapısıyla petrol, yağ ve yakıta karşı üstün direnç sağlayan endüstriyel eldiven. Otomotiv, madencilik ve yağ bazlı kimyasallarla çalışan sektörler için idealdir.',
    color: '#222',
    env: ['heavy-industry', 'assembly-general'],
    props: ['water-oil', 'chemical'],
  },
  {
    id: 'nitricl-300-11bf',
    name: 'NitriCL™ 300-11BF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/nitricl-300-11bf.png',
    material: 'nitrile', length: 'short',
    tags: ['Nitril', 'Temiz Oda', 'Pürüzsüz'],
    features: ['Clean Room Sınıfı', 'Düşük Partikül', 'Pürüzsüz Yüzey', 'Flok Astar'],
    specs: { 'Uzunluk': '300mm', 'Kalınlık': '0.45mm', 'Renk': 'Mavi', 'Astar': 'Flok' },
    desc: 'Temiz oda ve kontrollü üretim ortamları için özel nitril endüstriyel eldiven. Düşük partikül salınımı ile elektronik, ilaç ve hassas optik üretim süreçlerine uygundur.',
    color: '#003885',
    env: ['lab-precision', 'assembly-general'],
    props: ['precision'],
  },
  // ── EV TİPİ ──────────────────────────────────────────────────
  {
    id: 'nitroul-330-8sd',
    name: 'NitroUL™ 330-8SD',
    category: 'household', categoryLabel: 'Ev Tipi',
    img: '/products/household/nitroul-330-8sd.png',
    material: 'nitrile', length: 'medium',
    tags: ['Ev Tipi', 'Ultra İnce', 'Nitril'],
    features: ['Ultra İnce Nitril', 'Elmas Tutuş', 'Hafif', 'CE Kat. III'],
    specs: { 'Uzunluk': '330mm', 'Kalınlık': '0.20mm', 'Renk': 'Mavi', 'Astar': 'Yok' },
    desc: 'Ev ve genel temizlik işlemleri için tasarlanmış ultra ince nitril ev eldiveni. Elmas tutuş deseni ile ıslak ve kuru yüzeylerde güvenli kavrama, yüksek hassasiyet sunar.',
    color: '#003885',
    env: ['cleaning-household', 'assembly-general'],
    props: ['water-oil', 'precision'],
  },
  {
    id: 'naturasl-300-11bf',
    name: 'NaturaSL™ 300-11BF',
    category: 'household', categoryLabel: 'Ev Tipi',
    img: '/products/household/naturasl-300-11bf.png',
    material: 'natural', length: 'short',
    tags: ['Gümüş Astarlı', 'Aloe Vera', 'Ev Tipi'],
    features: ['Doğal Lateks', 'Gümüş Astar', 'Aloe Vera İçerikli', 'Anti-bacterial', 'Gıda Uyumlu'],
    specs: { 'Uzunluk': '300mm', 'Renk': 'Kobalt Mavi', 'Astar': 'Gümüş astar', 'Sertifika': 'EN 374' },
    desc: 'Aloe vera ve gümüş astar katkısıyla cildi besleyen, anti-bakteriyel doğal lateks ev eldiveni. Gıda uyumlu yapısıyla mutfak, temizlik ve çamaşır işlemleri için idealdir.',
    color: '#1255a8',
    env: ['cleaning-household', 'food-kitchen'],
    props: ['water-oil'],
    video: '/videos/naturasl.mp4',
  },
  // ── DİKİŞSİZ İŞ ELDİVENLERİ ─────────────────────────────────
  {
    id: 'neo-armor-ultra',
    name: 'NEO ARMOR ULTRA™ 1-083-Q11',
    category: 'seamless', categoryLabel: 'Dikişsiz İş Eldiveni',
    img: '/products/neo/neo-armor-ultra.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Darbe Koruması', 'Ultra Güçlü', 'Endüstriyel'],
    features: ['Sırt Koruması', 'TPR Darbe Emici', 'Anti-vibrasyon', 'Kesme Direnci'],
    specs: { 'Standart': 'EN 388', 'Darbe': 'KPA', 'Kaplama': 'Nitril köpük', 'Astar': 'HPPE' },
    desc: 'Sırt tarafındaki TPR darbe emici teknolojisiyle ağır endüstriyel ortamlarda elleri darbelerden koruyan dikişsiz iş eldiveni. İnşaat, maden ve ağır makine operasyonları için geliştirilmiştir.',
    color: '#1a5c8a',
    env: ['heavy-industry', 'assembly-general'],
    props: ['cut', 'abrasion'],
  },
  {
    id: 'neo-classic-001-a11',
    name: 'NEO CLASSIC™ 001-A11',
    category: 'seamless', categoryLabel: 'Dikişsiz İş Eldiveni',
    img: '/products/neo/neo-classic-001-a11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Nitril Köpük', 'Nefes Alabilir', 'Kesme A'],
    features: ['Nitril Köpük Kaplama', 'Hafif', 'Parmak Ucu Hassasiyeti', 'EN 388 Kat. A'],
    specs: { 'EN 388': '4131X', 'Kaplama': 'Nitril köpük', 'Astar': 'Naylon' },
    desc: 'Nitril köpük kaplamasıyla hem kuru hem ıslak tutuşta üstün performans sergileyen genel amaçlı dikişsiz iş eldiveni. Otomotiv, lojistik ve genel üretim ortamları için uygundur.',
    color: '#1a5c8a',
    env: ['assembly-general', 'heavy-industry'],
    props: ['water-oil'],
  },
  {
    id: 'neo-classic-031-a11',
    name: 'NEO CLASSIC™ 031-A11',
    category: 'seamless', categoryLabel: 'Dikişsiz İş Eldiveni',
    img: '/products/neo/neo-classic-031-a11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Nitril', 'Mavi', 'Genel Kullanım'],
    features: ['Tam Daldırma', 'Pürüzlü Bilek', 'Konfor Astar', 'EN 388 Kat. A'],
    specs: { 'EN 388': '4121X', 'Kaplama': 'Nitril', 'Astar': 'Naylon' },
    desc: 'Güçlü nitril kaplaması ve konforlu astarlı yapısıyla inşaat, lojistik ve genel endüstri için ideal dikişsiz iş eldiveni.',
    color: '#1a5c8a',
    env: ['assembly-general', 'heavy-industry'],
    props: ['water-oil', 'cut', 'abrasion'],
  },
  {
    id: 'neo-classic-044-f38',
    name: 'NEO CLASSIC™ 044-F38',
    category: 'seamless', categoryLabel: 'Dikişsiz İş Eldiveni',
    img: '/products/neo/neo-classic-044-f38.jpg',
    material: 'nitrile', length: 'medium',
    tags: ['Turuncu', 'Hi-Viz', 'Uzun Pazu'],
    features: ['Yüksek Görünürlük', 'Anti-slip', 'Uzun Pazu', 'EN 388'],
    specs: { 'EN 388': '4131X', 'Renk': 'Turuncu', 'Kaplama': 'Nitril köpük', 'Astar': 'Polyester' },
    desc: 'Yüksek görünürlük turuncu rengiyle güvenlik gerektiren ortamlara uygun uzun pazulu dikişsiz iş eldiveni. İnşaat ve dışarıda çalışma koşulları için tercih edilir.',
    color: '#c94000',
    env: ['heavy-industry', 'assembly-general'],
    props: ['water-oil', 'cut'],
  },
  {
    id: 'neo-classic-001-p11',
    name: 'NEO CLASSIC™ 001-P11',
    category: 'seamless', categoryLabel: 'Dikişsiz İş Eldiveni',
    img: '/products/neo/neo-classic-001-p11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Siyah', 'Pürüzlü', 'Kimyasal Direnç'],
    features: ['Pürüzlü Avuç', 'Anti-slip', 'Kimyasal Direnç', 'PU Kaplama'],
    specs: { 'EN 388': '4131X', 'Renk': 'Siyah', 'Kaplama': 'Nitril', 'Astar': 'Polyester' },
    desc: 'Pürüzlü nitril kaplamasıyla ıslak ve kuru yüzeylerde üstün tutuş sağlayan siyah dikişsiz iş eldiveni. Havacılık, mekanik montaj ve kimyasal temas gerektiren işler için geliştirilmiştir.',
    color: '#222',
    env: ['assembly-general', 'heavy-industry'],
    props: ['water-oil', 'chemical', 'cut', 'abrasion'],
  },
  {
    id: 'neo-classic-066-d11',
    name: 'NEO CLASSIC™ 066-D11',
    category: 'seamless', categoryLabel: 'Dikişsiz İş Eldiveni',
    img: '/products/neo/neo-classic-066-d11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Gri', 'Hassas İş', 'Çift Kaplama'],
    features: ['Çift Nitril Kaplama', 'Hassas Parmak Ucu', 'Nefes Alabilir Sırt', 'EN 388'],
    specs: { 'EN 388': '4131X', 'Renk': 'Gri', 'Kaplama': 'Nitril köpük', 'Astar': 'Naylon/Spandex' },
    desc: 'Çift nitril kaplaması ve nefes alabilen sırt tasarımıyla uzun vardiyalarda maksimum konfor sunan dikişsiz iş eldiveni. Hassas montaj ve kontrol işlemleri için uygundur.',
    color: '#555',
    env: ['assembly-general', 'lab-precision'],
    props: ['precision'],
  },
  {
    id: 'neo-lite-001-d11',
    name: 'NEO LITE™ 001-D11',
    category: 'seamless', categoryLabel: 'Dikişsiz İş Eldiveni',
    img: '/products/neo/neo-lite-001-d11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Ultra Hafif', 'Hassas', 'Lite Seri'],
    features: ['Ultra Hafif', 'İnce Nitril Köpük', 'Dokunmatik Uyumlu', 'Düşük Partikül'],
    specs: { 'EN 388': '4131X', 'Kaplama': 'İnce nitril köpük', 'Astar': 'İnce naylon' },
    desc: 'Neo Lite serisi ultra hafif yapısıyla hassas montaj, elektronik ve kontrol işlemleri için tasarlanmış dikişsiz iş eldiveni.',
    color: '#1a5c8a',
    env: ['lab-precision', 'assembly-general'],
    props: ['precision'],
  },
  {
    id: 'neo-lite-087-p11',
    name: 'NEO LITE™ 087-P11',
    category: 'seamless', categoryLabel: 'Dikişsiz İş Eldiveni',
    img: '/products/neo/neo-lite-087-p11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Lite', 'Lacivert', 'PU Kaplama'],
    features: ['PU Kaplama', 'Ultra İnce Polyester', 'Hafif Yapı', 'Kuru Tutuş'],
    specs: { 'EN 388': '4121X', 'Renk': 'Lacivert', 'Kaplama': 'Polyuretan', 'Astar': 'Polyester' },
    desc: 'Ultra ince PU kaplaması ve hafif polyester astarlı dikişsiz iş eldiveni. Otomotiv, lojistik, havacılık ve mekanik montaj sektörlerinde kuru koşullar için idealdir.',
    color: '#1a3a8a',
    env: ['assembly-general'],
    props: ['water-oil'],
  },
  {
    id: 'neo-lite-ultra-003-p11',
    name: 'NEO LITE ULTRA™ 003-P11',
    category: 'seamless', categoryLabel: 'Dikişsiz İş Eldiveni',
    img: '/products/neo/neo-lite-ultra-003-p11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Ultra Lite', 'Beyaz', 'Hassas Montaj'],
    features: ['Ultra İnce Astar', 'Minimal Ağırlık', 'Hassas İş', 'Optik Uyumlu'],
    specs: { 'EN 388': '4121X', 'Renk': 'Beyaz/Gri', 'Kaplama': 'Nitril köpük', 'Astar': 'Ultra ince naylon' },
    desc: 'Serideki en hafif model. Elektronik montaj, optik ve hassas parça üretimi için optimize edilmiş dikişsiz iş eldiveni. Minimum ağırlık ile maksimum hassasiyet sunar.',
    color: '#1a5c8a',
    env: ['lab-precision', 'assembly-general'],
    props: ['precision'],
  },
  {
    id: 'neo-fizz-lite-044-f38',
    name: 'Neo Fizz Lite™ 044-F38',
    category: 'seamless', categoryLabel: 'Dikişsiz İş Eldiveni',
    img: '/products/neo/neo-fizz-lite-044-f38.jpg',
    material: 'nitrile', length: 'medium',
    tags: ['Köpük Kaplama', 'Uzun Pazu', 'Islak Tutuş'],
    features: ['Fizz Nitril Köpük', 'Uzun Pazu', 'Hava Delikli Sırt', 'Islak & Kuru Tutuş'],
    specs: { 'EN 388': '4131X', 'Uzunluk': '380mm', 'Kaplama': 'Fizz nitril köpük', 'Astar': 'Naylon' },
    desc: 'Fizz nitril köpük teknolojisiyle kuru ve ıslak yüzeylerde üstün tutuş, uzun pazu tasarımıyla ek koruma sunan dikişsiz iş eldiveni.',
    color: '#c94000',
    env: ['assembly-general', 'heavy-industry'],
    props: ['water-oil', 'cut', 'abrasion'],
  },
];

export const CATEGORIES = [
  { id: 'all',        label: 'Tümü' },
  { id: 'food-safe',  label: 'Gıdaya Uygun' },
  { id: 'chemical',   label: 'Kimyasal' },
  { id: 'disposable', label: 'Tek Kullanımlık' },
  { id: 'industrial', label: 'Endüstriyel' },
  { id: 'household',  label: 'Ev Tipi' },
  { id: 'seamless',   label: 'Dikişsiz İş Eldiveni' },
] as const;
