export type ProductPictograms = {
  images?: { src: string; label: string }[];
};

export type Product = {
  id: string;
  name: string;
  category: 'food-safe' | 'chemical' | 'disposable' | 'industrial' | 'household' | 'seamless';
  categoryLabel: string;
  img: string;
  material: 'natural' | 'nitrile' | 'nbr';
  length: 'short' | 'medium' | 'long' | 'extra-long' | 'disposable';
  tags: string[];
  features: string[];
  specs: Record<string, string>;
  desc: string;
  color: string;
  env: ('heavy-industry' | 'assembly-general' | 'lab-precision' | 'food-kitchen' | 'cleaning-household')[];
  props: ('chemical' | 'water-oil' | 'cut' | 'abrasion' | 'heat' | 'cold' | 'disposable' | 'precision')[];
  coating?: 'pu' | 'foam-nitrile' | 'nitrile' | 'full-dip';
  datasheet?: string;
  video?: string;
  pictograms?: ProductPictograms;
};

export const PRODUCTS: Product[] = [
  // ── ÖNCELİKLİ ÜRÜNLER ────────────────────────────────────────
  {
    id: 'nitrofl-330-15sd',
    name: 'NitroFL™ 330-15SD',
    category: 'chemical', categoryLabel: 'Kimyasal',
    img: '/products/chemical/nitrofl-330-15sd.png',
    material: 'nitrile', length: 'medium',
    tags: ['Kimyasal Direnç', 'Kaymaz Tutuş', 'Virüs Bariyeri'],
    features: ['Tam Daldırma', 'Pürüzlü Yüzey', 'Uzun Pazu'],
    specs: { 'Uzunluk': '380mm', 'Kalınlık': '0.50mm', 'Renk': 'Yeşil', 'Astar': 'Pamuk flok' },
    desc: 'Zorlu kimyasal ortamlar için tasarlanmış nitril kauçuk eldiven. Kaymaz yüzeyi ve uzun pazu tasarımıyla kimyasal madde kullanılan sektörlerde üstün koruma sağlar.',
    color: '#003885',
    env: ['food-kitchen', 'lab-precision', 'heavy-industry', 'assembly-general'],
    props: ['chemical', 'water-oil'],
    coating: 'full-dip',
    datasheet: '/documents/nitrofl-330-15sd.pdf',
    pictograms: {
      images: [
        { src: '/pictograms/ce-cat3.png',           label: 'CE KKD Kategori III' },
        { src: '/pictograms/en-388.png',            label: 'EN 388:2016 — 4102X' },
        { src: '/pictograms/ajklmnopt.png',         label: 'EN ISO 374-1 Tip A · AJKLMNOPT' },
        { src: '/pictograms/en-374-5-virus.png',    label: 'EN ISO 374-5 · Virüs Koruması' },
        { src: '/pictograms/gidaya-uygun.png',      label: 'Gıdaya Uygun' },
        { src: '/pictograms/en-iso-21420.png',      label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'naturafl-300-15bf',
    name: 'NaturaFL™ 300-15BF',
    category: 'food-safe', categoryLabel: 'Gıdaya Uygun',
    img: '/products/industrial/naturafl-300-15bf.png',
    material: 'natural', length: 'medium',
    tags: ['Kobalt Mavi', 'Gıda Onaylı', 'Flok Astarlı'],
    features: ['Doğal Kauçuk', 'Gıda Temasına Uygun', 'Konforlu Astar', 'Kaymaz Tutus'],
    specs: { 'Uzunluk': '380mm', 'Kalınlık': '0.50mm', 'Renk': 'Kobalt Mavi', 'Astar': 'Pamuk flok' },
    desc: 'Gıda işleme ve konserve sektörü için onaylanmış kobalt mavi doğal lateks eldiven. Pamuk flok astarı ve balık pulu tutuş deseni ile uzun vardiyalarda yüksek konfor sağlar.',
    color: '#1255a8',
    env: ['food-kitchen', 'cleaning-household', 'assembly-general'],
    props: ['water-oil'],
    coating: 'full-dip',
    datasheet: '/documents/naturafl-300-15bf.pdf',
    video: '/videos/naturafl-300-15bf.mp4',
    pictograms: {
      images: [
        { src: '/pictograms/ce-2777.png',      label: 'CE 2777 · KKD Kategori III' },
        { src: '/pictograms/en-388.png',       label: 'EN 388:2016 — 1020X' },
        { src: '/pictograms/kmo.png',          label: 'EN ISO 374-1 Tip B · KMO' },
        { src: '/pictograms/gidaya-uygun.png', label: 'Gıdaya Uygun' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  // ── TEK KULLANIMLIK ───────────────────────────────────────────
  {
    id: 'lalan-2-8',
    name: 'Lalan LITE28™',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-2.8.png',
    material: 'nitrile', length: 'disposable',
    tags: ['2.8g', 'Ekonomik', 'Pudrasız'],
    features: ['Pudrasız', 'Lateks İçermez', 'Ambidextrous'],
    specs: { 'Kalınlık': '0.10mm', 'Ağırlık': '2.8g', 'Renk': 'Mavi', 'Paket': '100 adet/kutu' },
    desc: 'Hafif ve ekonomik tek kullanımlık nitril eldiven. Gıda, temizlik ve hafif koruma gerektiren işler için uygundur.',
    color: '#003885',
    env: ['food-kitchen', 'assembly-general', 'cleaning-household'],
    props: ['disposable', 'precision'],
    datasheet: '/documents/lalan-2-8.pdf',
    pictograms: {
      images: [
        { src: '/pictograms/gidaya-uygun.png', label: 'Gıdaya Uygun' },
      ],
    },
  },
  {
    id: 'lalan-lite-3-2',
    name: 'Lalan Lite™ 3.2',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-lite.png',
    material: 'nitrile', length: 'disposable',
    tags: ['Pudrasız', 'Tek Kullanımlık', 'Yüksek Hassasiyet'],
    features: ['Pudrasız', 'Lateks İçermez', 'Hafif Yapı', 'Hijyenik'],
    specs: { 'Kalınlık': '0.10mm', 'Ağırlık': '3.2g', 'Renk': 'Mavi/Gri', 'Sertifika': 'EN 455' },
    desc: 'Ultra ince nitril yapısıyla hassas işlemler ve tek kullanımlık hijyen gerektiren ortamlar için ideal. Pudrasız ve lateks içermez.',
    color: '#003885',
    env: ['food-kitchen', 'lab-precision', 'assembly-general', 'heavy-industry'],
    props: ['disposable', 'chemical', 'precision'],
    datasheet: '/documents/lalan-lite-3-2.pdf',
    pictograms: {
      images: [
        { src: '/pictograms/ce-2777.png',      label: 'CE 2777 · KKD Kategori III' },
        { src: '/pictograms/jkot.png',         label: 'EN ISO 374-1 Tip B · JKOT' },
        { src: '/pictograms/gidaya-uygun.png', label: 'Gıdaya Uygun' },
      ],
    },
  },
  {
    id: 'lalan-strong-f',
    name: 'Lalan Strong F™',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-strong-f.png',
    material: 'nitrile', length: 'disposable',
    tags: ['Güçlü', '5g', 'Dayanıklı'],
    features: ['Güçlendirilmiş Nitril', 'Parmak Ucu Pürüzlü', 'Ağır İş'],
    specs: { 'Kalınlık': '0.12mm', 'Ağırlık': '5.0g', 'Renk': 'Mavi', 'Paket': '100 adet/kutu' },
    desc: 'Standart tek kullanımlık eldivenlerden daha kalın nitril duvarıyla güçlü koruma. Temizlik, sanayi ve kimyasal temaslar için uygundur.',
    color: '#3a73bc',
    env: ['assembly-general', 'heavy-industry', 'lab-precision', 'food-kitchen'],
    props: ['disposable', 'chemical'],
    datasheet: '/documents/lalan-strong-f.pdf',
    pictograms: {
      images: [
        { src: '/pictograms/ce-2777.png',      label: 'CE 2777 · KKD Kategori III' },
        { src: '/pictograms/jkot.png',         label: 'EN ISO 374-1 Tip B · JKOT' },
        { src: '/pictograms/gidaya-uygun.png', label: 'Gıdaya Uygun' },
      ],
    },
  },
  {
    id: 'lalan-strong-x',
    name: 'Lalan Strong X™',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-strong-x.png',
    material: 'nitrile', length: 'disposable',
    tags: ['Extra Güçlü', '6.3g', 'Ağır Hizmet'],
    features: ['Extra Kalın Nitril', 'Pürüzlü Yüzey', 'Uzatılmış Bilek'],
    specs: { 'Kalınlık': '0.15mm', 'Ağırlık': '6.3g', 'Renk': 'Mavi/Siyah', 'Paket': '50 adet/kutu' },
    desc: 'Tek kullanımlık kategorinin en güçlü modeli. Ağır temizlik, kimyasal ve endüstriyel uygulamalar için sektörün en yüksek koruma seviyesi.',
    color: '#3a73bc',
    env: ['assembly-general', 'heavy-industry', 'lab-precision', 'food-kitchen'],
    props: ['disposable', 'chemical'],
    datasheet: '/documents/lalan-strong-x.pdf',
    pictograms: {
      images: [
        { src: '/pictograms/ce-2777.png',      label: 'CE 2777 · KKD Kategori III' },
        { src: '/pictograms/jkot.png',         label: 'EN ISO 374-1 Tip B · JKOT' },
        { src: '/pictograms/gidaya-uygun.png', label: 'Gıdaya Uygun' },
      ],
    },
  },
  {
    id: 'lalan-strong-x-esd',
    name: 'Lalan Strong X ESD™',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-strong-x-esd.png',
    material: 'nitrile', length: 'disposable',
    tags: ['ESD', 'Anti-statik', 'Elektronik'],
    features: ['ESD Korumalı', 'Anti-statik', 'Elektronik Sektör', 'Extra Kalın'],
    specs: { 'Kalınlık': '0.15mm', 'ESD': 'IEC 61340-5-1', 'Renk': 'Siyah', 'Paket': '50 adet/kutu' },
    desc: 'ESD (Elektrostatik Deşarj) korumalı formülasyonuyla elektronik üretim ve hassas bileşen montajı için geliştirilmiş özel nitril eldiven.',
    color: '#222',
    env: ['lab-precision', 'assembly-general', 'heavy-industry', 'food-kitchen'],
    props: ['disposable', 'chemical', 'precision'],
    datasheet: '/documents/lalan-strong-x-esd.pdf',
    pictograms: {
      images: [
        { src: '/pictograms/ce-2777.png',      label: 'CE 2777 · KKD Kategori III' },
        { src: '/pictograms/jkot.png',         label: 'EN ISO 374-1 Tip B · JKOT' },
        { src: '/pictograms/en-16350.png',     label: 'EN 16350 · ESD Antistatik' },
        { src: '/pictograms/gidaya-uygun.png', label: 'Gıdaya Uygun' },
      ],
    },
  },
  // ── KİMYASAL ────────────────────────────────────────────────
  {
    id: 'duonpfl-330-24sd',
    name: 'DUONPFL™ 330-24SD',
    category: 'chemical', categoryLabel: 'Kimyasal',
    img: '/products/chemical/duonpfl-330-24sd.png',
    material: 'nitrile', length: 'extra-long',
    tags: ['Çift Kaplama', 'Ekstra Uzun', 'Kimyasal Koruma'],
    features: ['Çift Daldırma Teknolojisi', 'Ekstra Uzun Pazu', 'Ağır Hizmet', 'CE Kat. III'],
    specs: { 'Uzunluk': '600mm', 'Kalınlık': '0.65mm', 'Renk': 'Yeşil/Sarı', 'Astar': 'Pamuk' },
    desc: 'Çift kaplama teknolojisiyle en zorlu kimyasal ortamlar için geliştirilmiş 60cm uzunluğunda nitril eldiven. İnşaat, kimya ve temizlik sektörlerine yönelik üst düzey kimyasal koruma sağlar.',
    color: '#004f11',
    env: ['heavy-industry'],
    props: ['chemical', 'water-oil', 'abrasion'],
    coating: 'full-dip',
    pictograms: {
      images: [
        { src: '/pictograms/ce-cat3.png', label: 'CE · KKD Kategori III' },
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 3121X' },
        { src: '/pictograms/aklmnop.png', label: 'EN ISO 374-1 Tip A · AKLMNOP' },
        { src: '/pictograms/en420.png', label: 'EN 420 · Genel Gereklilikler' },
      ],
    },
  },
  // ── ENDÜSTRİYEL ───────────────────────────────────────────────
  {
    id: 'naturafl-300-22sf',
    name: 'NaturaFL™ 300-22SF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturafl-300-22sf.png',
    material: 'natural', length: 'long',
    tags: ['Doğal Lateks', 'Süet Astarlı', 'Uzun'],
    features: ['Süet Astar', 'Gıda Uyumlu', 'Uzun Pazu', 'Konfor'],
    specs: { 'Uzunluk': '560mm', 'Kalınlık': '0.55mm', 'Renk': 'Sarı', 'Astar': 'Pamuk süet' },
    desc: 'Süet astarlı ve gıda sektörüne uygun uzun pazu doğal lateks endüstriyel eldiven. Balık işleme, konserve ve genel gıda üretimi için tercih edilir.',
    color: '#8c6500',
    env: ['food-kitchen', 'assembly-general', 'heavy-industry'],
    props: ['chemical', 'water-oil', 'abrasion'],
    coating: 'full-dip',
    pictograms: {
      images: [
        { src: '/pictograms/ce-cat3.png', label: 'CE · KKD Kategori III' },
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 3011X' },
        { src: '/pictograms/aklmnop.png', label: 'EN ISO 374-1 Tip A · AKLMNOP' },
      ],
    },
  },
  {
    id: 'naturafl-330-28bf',
    name: 'NaturaFL™ 330-28BF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturafl-330-28bf.png',
    material: 'natural', length: 'extra-long',
    tags: ['Doğal Lateks', 'Ekstra Uzun', 'Ağır Hizmet'],
    features: ['Ekstra Uzun Pazu', 'Kalın Kaplama', 'Güçlendirilmiş Yaka'],
    specs: { 'Uzunluk': '710mm', 'Kalınlık': '0.60mm', 'Renk': 'Sarı', 'Astar': 'Pamuk flok' },
    desc: 'Kimya ve petrokimya sektörü için geliştirilmiş ekstra uzun pazu doğal lateks endüstriyel eldiven. 710mm uzunluğuyla üst kola kadar tam koruma sağlar.',
    color: '#8c6500',
    env: ['heavy-industry'],
    props: ['chemical', 'water-oil'],
    coating: 'full-dip',
    pictograms: {
      images: [
        { src: '/pictograms/ce-cat3.png', label: 'CE · KKD Kategori III' },
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 1121A' },
        { src: '/pictograms/aklmopt.png', label: 'EN ISO 374-1 Tip A · AKLMOPT' },
      ],
    },
  },
  // ── EV TİPİ ──────────────────────────────────────────────────
  {
    id: 'nitroul-330-8sd',
    name: 'NitroUL™ 330-8SD',
    category: 'household', categoryLabel: 'Ev Tipi',
    img: '/products/household/nitroul-330-8sd.png',
    material: 'nitrile', length: 'medium',
    tags: ['Ev Tipi', 'Ultra İnce', 'Nitril'],
    features: ['Ultra İnce Nitril', 'Elmas Tutuş', 'Hafif', 'CE Kat. III'],
    specs: { 'Uzunluk': '330mm', 'Kalınlık': '0.20mm', 'Renk': 'Mavi', 'Astar': 'Yok' },
    desc: 'Ev ve genel temizlik işlemleri için tasarlanmış ultra ince nitril ev eldiveni. Elmas tutuş deseni ile ıslak ve kuru yüzeylerde güvenli kavrama, yüksek hassasiyet sunar.',
    color: '#003885',
    env: ['cleaning-household', 'assembly-general', 'heavy-industry'],
    props: ['chemical', 'water-oil'],
    coating: 'full-dip',
    pictograms: {
      images: [
        { src: '/pictograms/ce-cat3.png', label: 'CE · KKD Kategori III' },
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 2001X' },
        { src: '/pictograms/jkpt.png', label: 'EN ISO 374-1 Tip B · JKPT' },
        { src: '/pictograms/en-374-5-virus.png', label: 'EN ISO 374-5 · Virüs Koruması' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  // ── DİKİŞSİZ İŞ ELDİVENLERİ ─────────────────────────────────
  {
    id: 'neo-armor-ultra',
    name: 'NEO ARMOR ULTRA™ 1-083-Q11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-armor-ultra.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Darbe Koruması', 'Ultra Güçlü', 'Endüstriyel'],
    features: ['Sırt Koruması', 'TPR Darbe Emici', 'Anti-vibrasyon', 'Kesme Direnci'],
    specs: { 'Standart': 'EN 388', 'Darbe': 'KPA', 'Kaplama': 'Nitril köpük', 'Astar': 'HPPE' },
    desc: 'Sırt tarafındaki TPR darbe emici teknolojisiyle ağır endüstriyel ortamlarda elleri darbelerden koruyan dikişsiz iş eldiveni. İnşaat, maden ve ağır makine operasyonları için geliştirilmiştir.',
    color: '#1a5c8a',
    env: ['assembly-general', 'heavy-industry'],
    props: ['abrasion'],
    coating: 'foam-nitrile',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4131A' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-classic-001-a11',
    name: 'NEO CLASSIC™ 001-A11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-classic-001-a11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Nitril Köpük', 'Nefes Alabilir', 'Kesme A'],
    features: ['Nitril Köpük Kaplama', 'Hafif', 'Parmak Ucu Hassasiyeti', 'EN 388 Kat. A'],
    specs: { 'EN 388': '4131X', 'Kaplama': 'Nitril köpük', 'Astar': 'Naylon' },
    desc: 'Nitril köpük kaplamasıyla hem kuru hem ıslak tutuşta üstün performans sergileyen genel amaçlı dikişsiz iş eldiveni. Otomotiv, lojistik ve genel üretim ortamları için uygundur.',
    color: '#1a5c8a',
    env: ['assembly-general'],
    props: ['abrasion', 'heat'],
    coating: 'foam-nitrile',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4131A' },
        { src: '/pictograms/en-407.png', label: 'EN 407 · Isı ve Ateş Riski' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-classic-031-a11',
    name: 'NEO CLASSIC™ 031-A11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-classic-031-a11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Nitril', 'Mavi', 'Genel Kullanım'],
    features: ['Tam Daldırma', 'Pürüzlü Bilek', 'Konfor Astar', 'EN 388 Kat. A'],
    specs: { 'EN 388': '4121X', 'Kaplama': 'Nitril', 'Astar': 'Naylon' },
    desc: 'Güçlü nitril kaplaması ve konforlu astarlı yapısıyla inşaat, lojistik ve genel endüstri için ideal dikişsiz iş eldiveni.',
    color: '#1a5c8a',
    env: ['assembly-general'],
    props: ['abrasion'],
    coating: 'nitrile',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4121X' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-classic-044-f38',
    name: 'NEO CLASSIC™ 044-F38',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-classic-044-f38.jpg',
    material: 'nitrile', length: 'medium',
    tags: ['Turuncu', 'Hi-Viz', 'Uzun Pazu'],
    features: ['Yüksek Görünürlük', 'Anti-slip', 'Uzun Pazu', 'EN 388'],
    specs: { 'EN 388': '4131X', 'Renk': 'Turuncu', 'Kaplama': 'Nitril köpük', 'Astar': 'Polyester' },
    desc: 'Yüksek görünürlük turuncu rengiyle güvenlik gerektiren ortamlara uygun uzun pazulu dikişsiz iş eldiveni. İnşaat ve dışarıda çalışma koşulları için tercih edilir.',
    color: '#c94000',
    env: ['assembly-general', 'cleaning-household'],
    props: ['abrasion', 'water-oil', 'heat'],
    coating: 'foam-nitrile',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4141A' },
        { src: '/pictograms/en-407.png', label: 'EN 407 · Isı ve Ateş Riski' },
        { src: '/pictograms/en420.png', label: 'EN 420 · Genel Gereklilikler' },
      ],
    },
  },
  {
    id: 'neo-classic-001-p11',
    name: 'NEO CLASSIC™ 001-P11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-classic-001-p11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Siyah', 'Pürüzlü', 'Kimyasal Direnç'],
    features: ['Pürüzlü Avuç', 'Anti-slip', 'Kimyasal Direnç', 'PU Kaplama'],
    specs: { 'EN 388': '4131X', 'Renk': 'Siyah', 'Kaplama': 'Nitril', 'Astar': 'Polyester' },
    desc: 'Pürüzlü nitril kaplamasıyla ıslak ve kuru yüzeylerde üstün tutuş sağlayan siyah dikişsiz iş eldiveni. Havacılık, mekanik montaj ve kimyasal temas gerektiren işler için geliştirilmiştir.',
    color: '#222',
    env: ['assembly-general', 'heavy-industry', 'lab-precision'],
    props: ['abrasion', 'water-oil', 'precision', 'heat'],
    coating: 'nitrile',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4131A' },
        { src: '/pictograms/en-407.png', label: 'EN 407 · Isı ve Ateş Riski' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-classic-066-d11',
    name: 'NEO CLASSIC™ 066-D11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-classic-066-d11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Gri', 'Hassas İş', 'Çift Kaplama'],
    features: ['Çift Nitril Kaplama', 'Hassas Parmak Ucu', 'Nefes Alabilir Sırt', 'EN 388'],
    specs: { 'EN 388': '4131X', 'Renk': 'Gri', 'Kaplama': 'Nitril köpük', 'Astar': 'Naylon/Spandex' },
    desc: 'Çift nitril kaplaması ve nefes alabilen sırt tasarımıyla uzun vardiyalarda maksimum konfor sunan dikişsiz iş eldiveni. Hassas montaj ve kontrol işlemleri için uygundur.',
    color: '#555',
    env: ['assembly-general'],
    props: ['abrasion', 'water-oil'],
    coating: 'foam-nitrile',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4121X' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-lite-001-d11',
    name: 'NEO LITE™ 001-D11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-lite-001-d11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Ultra Hafif', 'Hassas', 'Lite Seri'],
    features: ['Ultra Hafif', 'İnce Nitril Köpük', 'Dokunmatik Uyumlu', 'Düşük Partikül'],
    specs: { 'EN 388': '4131X', 'Kaplama': 'İnce nitril köpük', 'Astar': 'İnce naylon' },
    desc: 'Neo Lite serisi ultra hafif yapısıyla hassas montaj, elektronik ve kontrol işlemleri için tasarlanmış dikişsiz iş eldiveni.',
    color: '#1a5c8a',
    env: ['assembly-general', 'lab-precision'],
    props: ['abrasion', 'precision'],
    coating: 'foam-nitrile',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4131X' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-lite-087-p11',
    name: 'NEO LITE™ 087-P11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-lite-087-p11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Lite', 'Lacivert', 'PU Kaplama'],
    features: ['PU Kaplama', 'Ultra İnce Polyester', 'Hafif Yapı', 'Kuru Tutuş'],
    specs: { 'EN 388': '4121X', 'Renk': 'Lacivert', 'Kaplama': 'Polyuretan', 'Astar': 'Polyester' },
    desc: 'Ultra ince PU kaplaması ve hafif polyester astarlı dikişsiz iş eldiveni. Otomotiv, lojistik, havacılık ve mekanik montaj sektörlerinde kuru koşullar için idealdir.',
    color: '#1a3a8a',
    env: ['assembly-general', 'heavy-industry'],
    props: ['abrasion', 'water-oil', 'precision'],
    coating: 'pu',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 3121A' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-lite-ultra-003-p11',
    name: 'NEO LITE ULTRA™ 003-P11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-lite-ultra-003-p11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Ultra Lite', 'Beyaz', 'Hassas Montaj'],
    features: ['Ultra İnce Astar', 'Minimal Ağırlık', 'Hassas İş', 'Optik Uyumlu'],
    specs: { 'EN 388': '4121X', 'Renk': 'Beyaz/Gri', 'Kaplama': 'Nitril köpük', 'Astar': 'Ultra ince naylon' },
    desc: 'Serideki en hafif model. Elektronik montaj, optik ve hassas parça üretimi için optimize edilmiş dikişsiz iş eldiveni. Minimum ağırlık ile maksimum hassasiyet sunar.',
    color: '#1a5c8a',
    env: ['assembly-general', 'lab-precision'],
    props: ['abrasion', 'water-oil', 'precision', 'heat'],
    coating: 'foam-nitrile',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 3121X' },
        { src: '/pictograms/en-407.png', label: 'EN 407 · Isı ve Ateş Riski' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-fizz-lite-044-f38',
    name: 'Neo Fizz Lite™ 044-F38',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-fizz-lite-044-f38.jpg',
    material: 'nitrile', length: 'medium',
    tags: ['Köpük Kaplama', 'Uzun Pazu', 'Islak Tutuş'],
    features: ['Fizz Nitril Köpük', 'Uzun Pazu', 'Hava Delikli Sırt', 'Islak & Kuru Tutuş'],
    specs: { 'EN 388': '4131X', 'Uzunluk': '380mm', 'Kaplama': 'Fizz nitril köpük', 'Astar': 'Naylon' },
    desc: 'Fizz nitril köpük teknolojisiyle kuru ve ıslak yüzeylerde üstün tutuş, uzun pazu tasarımıyla ek koruma sunan dikişsiz iş eldiveni.',
    color: '#c94000',
    env: ['assembly-general', 'cleaning-household'],
    props: ['abrasion', 'water-oil', 'heat'],
    coating: 'foam-nitrile',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4141A' },
        { src: '/pictograms/en-407.png', label: 'EN 407 · Isı ve Ateş Riski' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-armor-2-007-b11',
    name: 'NEO ARMOR™ 2-007-B11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-armor-2-007-b11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Nitril Köpük', 'Isı Direnci', 'Başparmak Takviyesi'],
    features: ['Nitril Köpük Avuç Kaplama', 'Başparmak Arası Takviye', 'EN 407 Isı Direnci', 'EN 388 4X43B'],
    specs: { 'EN 388': '4X43B', 'EN 407': 'Isı direnci', 'Kaplama': 'Nitril köpük', 'Astar': 'Örme' },
    desc: 'Başparmak arası takviyeli nitril köpük avuç kaplamasıyla ıslak ve yağlı ortamlarda güvenli tutuş sağlayan dikişsiz iş eldiveni. EN 407 ısı direnci ile montaj ve genel endüstriyel işler için uygundur.',
    color: '#1a5c8a',
    env: ['assembly-general', 'heavy-industry'],
    props: ['abrasion', 'water-oil', 'heat'],
    coating: 'foam-nitrile',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4X43B' },
        { src: '/pictograms/en-407.png', label: 'EN 407 · Isı ve Ateş Riski' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-armor-2-056-q11',
    name: 'NEO ARMOR™ 2-056-Q11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-armor-2-056-q11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['PU Kaplama', 'HPPE Astar', 'Hassas Tutuş'],
    features: ['Poliüretan Avuç Kaplama', 'HPPE / Naylon / Spandex Astar', 'EN 407 Isı Direnci', 'Parmak Ucu Hassasiyeti'],
    specs: { 'EN 388': '4X43X', 'EN 407': 'Isı direnci', 'Kaplama': 'Poliüretan', 'Astar': 'HPPE / Naylon / Spandex' },
    desc: 'Orta ağırlıkta poliüretan kaplaması ve HPPE karışımı astarıyla hassasiyet ve dayanıklılığı bir arada sunan dikişsiz iş eldiveni. İnce montaj ve genel üretim işleri için idealdir.',
    color: '#1a5c8a',
    env: ['assembly-general', 'heavy-industry'],
    props: ['abrasion', 'water-oil', 'heat'],
    coating: 'pu',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4X43B' },
        { src: '/pictograms/en-407.png', label: 'EN 407 · Isı ve Ateş Riski' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-armor-3-017-b11',
    name: 'NEO ARMOR™ 3-017-B11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-armor-3-017-b11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Nitril Köpük', 'HPPE Astar', 'Isı Direnci'],
    features: ['Nitril Köpük Avuç Kaplama', 'Başparmak Arası Takviye', 'HPPE / Naylon Astar', 'EN 407 Isı Direnci'],
    specs: { 'Standart': 'EN 388 / EN 407', 'Kaplama': 'Nitril köpük', 'Astar': 'HPPE / Naylon' },
    desc: 'HPPE karışımı astarı ve başparmak arası takviyesiyle dayanıklı kavrama sunan nitril köpük kaplı dikişsiz iş eldiveni. EN 407 ısı direnci ile genel endüstriyel kullanıma uygundur.',
    color: '#1a5c8a',
    env: ['assembly-general', 'heavy-industry'],
    props: ['water-oil', 'heat'],
    coating: 'foam-nitrile',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4X43C' },
        { src: '/pictograms/en-407.png', label: 'EN 407 · Isı ve Ateş Riski' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-armor-3-036-q11',
    name: 'NEO ARMOR™ 3-036-Q11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-armor-3-036-q11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['PU Kaplama', 'HPPE-Cam Astar', 'Isı Direnci'],
    features: ['Poliüretan Avuç Kaplama', 'HPPE / Cam / Polyester Astar', 'EN 407 Isı Direnci', 'Yüksek Aşınma Direnci'],
    specs: { 'EN 388': '4X43X', 'EN 407': 'Isı direnci', 'Kaplama': 'Poliüretan', 'Astar': 'HPPE / Cam / Polyester' },
    desc: 'Cam elyaf takviyeli HPPE astarı ve poliüretan kaplamasıyla yüksek aşınma direnci sunan dikişsiz iş eldiveni. Ağır montaj ve endüstriyel elleçleme işleri için geliştirilmiştir.',
    color: '#1a5c8a',
    env: ['assembly-general', 'heavy-industry'],
    props: ['abrasion', 'water-oil', 'heat'],
    coating: 'pu',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4X43C' },
        { src: '/pictograms/en-407.png', label: 'EN 407 · Isı ve Ateş Riski' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-armor-3-185-q11',
    name: 'NEO ARMOR™ 3-185-Q11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-armor-3-185-q11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Kesme C', 'Ultra Hafif', 'HPPE-Çelik Astar'],
    features: ['TDM Kesme Seviyesi C', 'Ultra Hafif Poliüretan Kaplama', 'HPPE / Çelik / Cam Astar', 'EN 388 3X42C'],
    specs: { 'EN 388': '3X42C', 'Kesme (TDM)': 'C', 'Kaplama': 'Poliüretan', 'Astar': 'HPPE / Çelik / Cam' },
    desc: 'Çelik ve cam elyaf takviyeli HPPE astarıyla TDM Seviye C kesme direnci sunan, ultra hafif poliüretan kaplı dikişsiz iş eldiveni. Kesici malzeme elleçleyen montaj hatları için uygundur.',
    color: '#1a5c8a',
    env: ['assembly-general', 'heavy-industry'],
    props: ['abrasion', 'cut', 'water-oil'],
    coating: 'pu',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 3X42C' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-armor-4-032-b11',
    name: 'NEO ARMOR™ 4-032-B11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-armor-4-032-b11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Kesme E', 'Nitril Köpük', 'Isı Direnci'],
    features: ['TDM Kesme Seviyesi E', 'Nitril Köpük Avuç Kaplama', 'HPPE Astar', 'EN 407 Isı Direnci'],
    specs: { 'EN 388': '4X44E', 'Kesme (TDM)': 'E', 'EN 407': 'Isı direnci', 'Kaplama': 'Nitril köpük', 'Astar': 'HPPE' },
    desc: 'HPPE astarı ve nitril köpük kaplamasıyla TDM Seviye E yüksek kesme direnci sunan dikişsiz iş eldiveni. Sac, cam ve keskin kenarlı malzeme elleçleyen ağır endüstriyel işler için geliştirilmiştir.',
    color: '#1a5c8a',
    env: ['assembly-general', 'heavy-industry'],
    props: ['abrasion', 'cut', 'water-oil', 'heat'],
    coating: 'foam-nitrile',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4X44E' },
        { src: '/pictograms/en-407.png', label: 'EN 407 · Isı ve Ateş Riski' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-armor-6-188-q11',
    name: 'NEO ARMOR™ 6-188-Q11',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-armor-6-188-q11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['HPPE-Çelik Astar', 'PU Kaplama', 'Dikişsiz'],
    features: ['HPPE / Çelik / Cam Örme Astar', '5 Parmaklı Yapı', 'Poliüretan Kaplama', 'EN 388'],
    specs: { 'Standart': 'EN 388', 'Kaplama': 'Poliüretan', 'Astar': 'HPPE / Çelik / Cam' },
    desc: 'Çelik ve cam elyaf takviyeli HPPE örme yapısıyla dayanıklılık sunan, poliüretan kaplı dikişsiz iş eldiveni. Genel endüstriyel elleçleme ve montaj işleri için uygundur.',
    color: '#1a5c8a',
    env: ['assembly-general', 'heavy-industry'],
    props: ['water-oil'],
    coating: 'pu',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4X42F' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-chem-1-121-x96',
    name: 'NEO CHEM™ 1-121-X96',
    category: 'chemical', categoryLabel: 'Kimyasal',
    img: '/products/neo/neo-chem-1-121-x96.jpg',
    material: 'nitrile', length: 'medium',
    tags: ['Kimyasal Koruma', 'NBR Tam Kaplama', 'EN ISO 374'],
    features: ['Çift Daldırma NBR Tam Kaplama', 'EN ISO 374 Kimyasal Koruma', 'EN 407 Isı Direnci', 'Naylon / Spandex Astar'],
    specs: { 'EN ISO 374': 'Kimyasal koruma', 'EN 407': 'Isı direnci', 'Kaplama': 'NBR (çift daldırma)', 'Astar': 'Naylon / Spandex' },
    desc: 'Çift daldırma NBR tam kaplamasıyla kimyasal sıçramalara karşı koruma sağlayan dikişsiz eldiven. EN ISO 374 ve EN 407 sertifikalarıyla kimya, laboratuvar ve endüstriyel temizlik uygulamaları için uygundur.',
    color: '#1a5c8a',
    env: ['heavy-industry', 'lab-precision', 'assembly-general'],
    props: ['chemical', 'heat'],
    coating: 'full-dip',
    pictograms: {
      images: [
        { src: '/pictograms/ce-2777.png', label: 'CE 2777 · KKD Kategori III' },
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4142A' },
        { src: '/pictograms/jklmno.png', label: 'EN ISO 374-1 Tip A · JKLMNO' },
        { src: '/pictograms/en-374-5-virus.png', label: 'EN ISO 374-5 · Virüs Koruması' },
        { src: '/pictograms/en-407.png', label: 'EN 407 · Isı ve Ateş Riski' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-fizz-042-d76',
    name: 'NEO FIZZ™ 042-D76',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-fizz-042-d76.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Nitril Çift Kaplama', 'Sıvı Bariyeri', 'Isı Direnci'],
    features: ['Tam Daldırma Düz Nitril', 'Avuç İçi Köpük Nitril', 'EN 407 Isı Direnci', 'EN 388 4131A'],
    specs: { 'EN 388': '4131A', 'EN 407': 'Isı direnci', 'Kaplama': 'Nitril (tam + köpük)', 'Astar': 'Örme' },
    desc: 'Tam daldırma düz nitril tabanı ve avuç içi köpük nitril kaplamasıyla sıvı bariyeri ve güvenli tutuş sağlayan dikişsiz iş eldiveni. Yağlı ve ıslak ortamlardaki montaj işleri için uygundur.',
    color: '#1a5c8a',
    env: ['assembly-general', 'heavy-industry'],
    props: ['abrasion', 'water-oil', 'heat'],
    coating: 'foam-nitrile',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4131A' },
        { src: '/pictograms/en-407.png', label: 'EN 407 · Isı ve Ateş Riski' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-frost-077-f11',
    name: 'NEO FROST™ 077-F11',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/neo/neo-frost-077-f11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Soğuk Koruma', 'Polar Astar', 'NBR Çift Kaplama'],
    features: ['EN 511 Soğuk Koruması', 'Çift Kat NBR Kaplama', 'Termal Polar Astar', 'EN 407 Isı Direnci'],
    specs: { 'EN 388': '4232B', 'EN 511': 'Soğuk koruma', 'EN 407': 'Isı direnci', 'Kaplama': 'NBR (çift kat)', 'Astar': 'Naylon + Polar' },
    desc: 'Termal polar astarı ve çift kat NBR kaplamasıyla soğuk ortamlarda el ısısını koruyan dikişsiz iş eldiveni. EN 511 soğuk koruması ile soğuk hava depoları ve dış saha çalışmaları için geliştirilmiştir.',
    color: '#1a5c8a',
    env: ['heavy-industry', 'assembly-general'],
    props: ['abrasion', 'water-oil', 'heat', 'cold'],
    coating: 'full-dip',
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 4232B' },
        { src: '/pictograms/en-407.png', label: 'EN 407 · Isı ve Ateş Riski' },
        { src: '/pictograms/en-511.png', label: 'EN 511 · Soğuk Riski' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
  {
    id: 'neo-pure-5-091-c00',
    name: 'NEO PURE™ 5-091-C00',
    category: 'seamless', categoryLabel: 'Dikişsiz Örme Eldiven',
    img: '/products/neo/neo-pure-5-091-c00.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Kesme E', 'Antimikrobiyal', 'HPPE-Çelik Astar'],
    features: ['TDM Kesme Seviyesi E', 'Antimikrobiyal İşlem', 'HPPE / Çelik / Polyester Astar', 'EN 388 2X4XE'],
    specs: { 'EN 388': '2X4XE', 'Kesme (TDM)': 'E', 'İşlem': 'Antimikrobiyal', 'Astar': 'HPPE / Çelik / Polyester' },
    desc: 'Çelik takviyeli HPPE astarıyla TDM Seviye E kesme direnci sunan, antimikrobiyal işlemli dikişsiz iş eldiveni. Hijyenin önemli olduğu hassas montaj ve laboratuvar uygulamaları için uygundur.',
    color: '#1a5c8a',
    env: ['lab-precision', 'assembly-general'],
    props: ['cut', 'water-oil', 'heat'],
    pictograms: {
      images: [
        { src: '/pictograms/en-388.png', label: 'EN 388:2016 — 2X4XE' },
        { src: '/pictograms/en-407.png', label: 'EN 407 · Isı ve Ateş Riski' },
        { src: '/pictograms/en-iso-21420.png', label: 'EN ISO 21420' },
      ],
    },
  },
];

export const CATEGORIES = [
  { id: 'all',        label: 'Tümü' },
  { id: 'food-safe',  label: 'Gıdaya Uygun' },
  { id: 'chemical',   label: 'Kimyasal' },
  { id: 'disposable', label: 'Tek Kullanımlık' },
  { id: 'industrial', label: 'Endüstriyel' },
  { id: 'household',  label: 'Ev Tipi' },
  { id: 'seamless',   label: 'Dikişsiz Örme Eldiven' },
] as const;
