export type Product = {
  id: string;
  name: string;
  category: 'industrial' | 'neo' | 'household' | 'disposable';
  categoryLabel: string;
  img: string;
  material: 'natural' | 'nitrile' | 'nbr' | 'disposable-nitrile';
  length: 'short' | 'medium' | 'long' | 'extra-long' | 'disposable';
  tags: string[];
  features: string[];
  specs: Record<string, string>;
  desc: string;
  color: string;
  // glove finder filters
  usage: ('industrial' | 'chemical' | 'household' | 'medical-food' | 'esd')[];
  risk: ('low' | 'medium' | 'heavy')[];
};

export const PRODUCTS: Product[] = [
  // ── ENDÜSTRİYEL ───────────────────────────────────────────────
  {
    id: 'nitrofl-330-15sd',
    name: 'NitroFL™ 330-15SD',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/nitrofl-330-15sd.jpg',
    material: 'nitrile', length: 'medium',
    tags: ['Kimyasal Direnç', 'Kaymaz Tutuş', 'Kesme Dayanımı'],
    features: ['Tam Daldırma', 'Pürüzlü Yüzey', 'Uzun Pazu'],
    specs: { 'Uzunluk': '380mm', 'Kalınlık': '0.50mm', 'Renk': 'Yeşil', 'Astar': 'Pamuk flok' },
    desc: 'Zorlu kimyasal ortamlar için tasarlanmış nitril kauçuk eldiven. Kaymaz yüzeyi ve uzun pazu tasarımıyla kimyasal madde kullanılan sektörlerde üstün koruma sağlar.',
    color: '#003885',
    usage: ['industrial', 'chemical'], risk: ['medium', 'heavy'],
  },
  {
    id: 'nitrofl-330-18sf',
    name: 'NitroFL™ 330-18SF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/nitrofl-330-18sf.png',
    material: 'nitrile', length: 'long',
    tags: ['Kimyasal Direnç', 'Uzun Pazu', 'Endüstriyel'],
    features: ['Süet Astarlı', 'Uzatılmış Pazu', 'Anti-slip'],
    specs: { 'Uzunluk': '460mm', 'Kalınlık': '0.55mm', 'Renk': 'Mavi', 'Astar': 'Flock' },
    desc: 'Uzun pazu tasarımıyla kolları da koruyan nitril eldiven. Ağır sanayi ve kimyasal ortamlara uygundur.',
    color: '#003885',
    usage: ['industrial', 'chemical'], risk: ['medium', 'heavy'],
  },
  {
    id: 'duonpfl-330-24sd',
    name: 'DUONPFL™ 330-24SD',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/duonpfl-330-24sd.jpg',
    material: 'nitrile', length: 'extra-long',
    tags: ['Çift Bileşen', 'Ekstra Uzun', 'Kimyasal Koruma'],
    features: ['Çift Daldırma', 'Ekstra Uzun Pazu', 'Ağır Hizmet'],
    specs: { 'Uzunluk': '600mm', 'Kalınlık': '0.65mm', 'Renk': 'Yeşil/Sarı', 'Astar': 'Pamuk' },
    desc: 'Çift kaplama teknolojisiyle en zorlu kimyasal ortamlar için geliştirilmiş. 60cm uzunluğuyla kola ekstra koruma sağlar.',
    color: '#004f11',
    usage: ['chemical'], risk: ['heavy'],
  },
  {
    id: 'naturafl-300-11bf',
    name: 'NaturaFL™ 300-11BF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturafl-300-11bf.jpg',
    material: 'natural', length: 'short',
    tags: ['Doğal Lateks', 'Flok Astarlı', 'Genel Endüstri'],
    features: ['Doğal Kauçuk', 'Flok Astar', 'Kaymaz Parmak'],
    specs: { 'Uzunluk': '300mm', 'Kalınlık': '0.50mm', 'Renk': 'Sarı', 'Astar': 'Pamuk flok' },
    desc: 'Doğal lateksin esnekliğini endüstriyel dayanıklılıkla buluşturan flok astarlı eldiven.',
    color: '#8c6500',
    usage: ['industrial'], risk: ['low', 'medium'],
  },
  {
    id: 'naturafl-300-15bf',
    name: 'NaturaFL™ 300-15BF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturafl-300-15bf.webp',
    material: 'natural', length: 'medium',
    tags: ['Doğal Lateks', 'Orta Uzunluk', 'Flok Astarlı'],
    features: ['Doğal Kauçuk', 'Uzun Pazu', 'Konforlu Astar'],
    specs: { 'Uzunluk': '380mm', 'Kalınlık': '0.50mm', 'Renk': 'Sarı', 'Astar': 'Pamuk flok' },
    desc: 'Orta boy pazu uzunluğuyla endüstriyel ortamlarda kola ek koruma sağlayan doğal lateks eldiven.',
    color: '#8c6500',
    usage: ['industrial'], risk: ['low', 'medium'],
  },
  {
    id: 'naturafl-300-22sf',
    name: 'NaturaFL™ 300-22SF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturafl-300-22sf.webp',
    material: 'natural', length: 'long',
    tags: ['Doğal Lateks', 'Süet Astarlı', 'Uzun'],
    features: ['Süet Astar', 'Gıda Uyumlu', 'Uzun Pazu'],
    specs: { 'Uzunluk': '560mm', 'Kalınlık': '0.55mm', 'Renk': 'Sarı', 'Astar': 'Pamuk süet' },
    desc: 'Süet astarlı ve gıda sektörüne uygun uzun pazu doğal lateks eldiven.',
    color: '#8c6500',
    usage: ['industrial', 'medical-food'], risk: ['low', 'medium'],
  },
  {
    id: 'naturafl-330-28bf',
    name: 'NaturaFL™ 330-28BF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturafl-330-28bf.webp',
    material: 'natural', length: 'extra-long',
    tags: ['Doğal Lateks', 'Ekstra Uzun', 'Ağır Hizmet'],
    features: ['Ekstra Uzun Pazu', 'Kalın Kaplama', 'Güçlendirilmiş Yaka'],
    specs: { 'Uzunluk': '710mm', 'Kalınlık': '0.60mm', 'Renk': 'Sarı', 'Astar': 'Pamuk flok' },
    desc: 'Kimya ve petrokimya sektörü için geliştirilmiş ekstra uzun pazu doğal lateks eldiven.',
    color: '#8c6500',
    usage: ['industrial', 'chemical'], risk: ['medium', 'heavy'],
  },
  {
    id: 'naturahd-330-32b',
    name: 'NaturaHD™ 330-32B',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturahd-330-32b.webp',
    material: 'natural', length: 'extra-long',
    tags: ['Ağır Hizmet', 'Ekstra Uzun', 'Yüksek Kalınlık'],
    features: ['HD Formülasyon', 'Ekstra Kalın', 'Uzun Pazu'],
    specs: { 'Uzunluk': '810mm', 'Kalınlık': '0.80mm', 'Renk': 'Sarı/Kahve', 'Astar': 'Pamuk' },
    desc: 'En ağır sanayi uygulamaları için geliştirilmiş yüksek yoğunluklu (HD) doğal lateks eldiven.',
    color: '#6b4c00',
    usage: ['industrial', 'chemical'], risk: ['heavy'],
  },
  {
    id: 'naturaul-300-12bf',
    name: 'NaturaUL™ 300-12BF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturaul-300-12bf.webp',
    material: 'natural', length: 'short',
    tags: ['Ultra İnce', 'Yüksek Hassasiyet', 'Lateks'],
    features: ['Ultra İnce (UL)', 'Hassas Tutuş', 'Gıda Uyumlu'],
    specs: { 'Uzunluk': '305mm', 'Kalınlık': '0.25mm', 'Renk': 'Krem', 'Astar': 'Yok (pürüzsüz)' },
    desc: 'Ultra ince lateks duvarıyla maksimum hassasiyet sağlayan, laboratuvar ve gıda sektörü için ideal eldiven.',
    color: '#c87c00',
    usage: ['industrial', 'medical-food'], risk: ['low'],
  },
  {
    id: 'naturaul-300-15bf',
    name: 'NaturaUL™ 300-15BF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/naturaul-300-15bf.webp',
    material: 'natural', length: 'medium',
    tags: ['Ultra İnce', 'Uzun Pazu', 'Lateks'],
    features: ['Ultra İnce (UL)', 'Orta Boy Pazu', 'Hassas Dokunuş'],
    specs: { 'Uzunluk': '380mm', 'Kalınlık': '0.25mm', 'Renk': 'Krem', 'Astar': 'Yok' },
    desc: 'Ultra ince lateks yapısıyla maksimum hassasiyet, orta boy pazusuyla ek koruma sunar.',
    color: '#c87c00',
    usage: ['industrial', 'medical-food'], risk: ['low'],
  },
  {
    id: 'nbrfl-300-11bf',
    name: 'NBRFL™ 300-11BF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/nbrfl-300-11bf.webp',
    material: 'nbr', length: 'short',
    tags: ['NBR', 'Yağ Direnci', 'Flok Astarlı'],
    features: ['NBR Kauçuk', 'Yağ & Yakıt Direnci', 'Flok Astar'],
    specs: { 'Uzunluk': '300mm', 'Kalınlık': '0.50mm', 'Renk': 'Siyah', 'Astar': 'Pamuk flok' },
    desc: 'NBR (Nitril-Bütadien Kauçuk) yapısıyla petrol, yağ ve yakıta karşı üstün direnç sağlayan endüstriyel eldiven.',
    color: '#222',
    usage: ['industrial', 'chemical'], risk: ['medium'],
  },
  {
    id: 'nitricl-300-11bf',
    name: 'NitriCL™ 300-11BF',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/nitricl-300-11bf.webp',
    material: 'nitrile', length: 'short',
    tags: ['Nitril', 'Temiz Oda', 'Pürüzsüz'],
    features: ['Clean Room Sınıfı', 'Düşük Partikül', 'Pürüzsüz Yüzey'],
    specs: { 'Uzunluk': '300mm', 'Kalınlık': '0.45mm', 'Renk': 'Mavi', 'Astar': 'Flok' },
    desc: 'Temiz oda ve kontrollü üretim ortamları için özel nitril eldiven. Düşük partikül salınımı ile kritik süreçlere uygundur.',
    color: '#003885',
    usage: ['industrial', 'esd'], risk: ['low', 'medium'],
  },
  {
    id: 'nitroul-330-8sd',
    name: 'NitroUL™ 330-8SD',
    category: 'industrial', categoryLabel: 'Endüstriyel',
    img: '/products/industrial/nitroul-330-8sd.webp',
    material: 'nitrile', length: 'medium',
    tags: ['Ultra İnce', 'Nitril', 'Hassas İş'],
    features: ['Ultra İnce Nitril', 'Anti-slip', 'Hafif'],
    specs: { 'Uzunluk': '330mm', 'Kalınlık': '0.20mm', 'Renk': 'Mavi', 'Astar': 'Yok' },
    desc: 'Ultra ince nitril yapısıyla hassas çalışmalar için yüksek dokunma hassasiyeti ve kimyasal direnç sunar.',
    color: '#003885',
    usage: ['industrial', 'medical-food'], risk: ['low'],
  },
  // ── NEO SERİSİ ────────────────────────────────────────────────
  {
    id: 'neo-armor-ultra',
    name: 'NEO ARMOR ULTRA™ 1-083-Q11',
    category: 'neo', categoryLabel: 'Neo Serisi',
    img: '/products/neo/neo-armor-ultra.jpg',
    material: 'nitrile', length: 'medium',
    tags: ['Darbe Koruması', 'Ultra Güçlü', 'Endüstriyel'],
    features: ['Sırt Koruması', 'TPR Darbe Emici', 'Anti-vibrasyon'],
    specs: { 'Standart': 'EN 388', 'Darbe': 'KPA', 'Kaplama': 'Nitril köpük', 'Astar': 'HPPE' },
    desc: 'Sırt tarafındaki TPR darbe emici teknolojisiyle ağır endüstriyel ortamlarda elleri darbelerden koruyan üst düzey iş eldiveni.',
    color: '#1a5c8a',
    usage: ['industrial'], risk: ['heavy'],
  },
  {
    id: 'neo-classic-001-a11',
    name: 'NEO CLASSIC™ 001-A11',
    category: 'neo', categoryLabel: 'Neo Serisi',
    img: '/products/neo/neo-classic-001-a11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Nitril Köpük', 'Nefes Alabilir', 'Hassas İş'],
    features: ['Nitril Köpük Kaplama', 'Hafif', 'Parmak Ucu Hassasiyeti'],
    specs: { 'EN 388': '4131X', 'Kaplama': 'Nitril köpük', 'Astar': 'Naylon' },
    desc: 'Nitril köpük kaplamasıyla hem kuru hem ıslak tutuşta üstün performans sergileyen genel amaçlı iş eldiveni.',
    color: '#1a5c8a',
    usage: ['industrial'], risk: ['low', 'medium'],
  },
  {
    id: 'neo-classic-031-a11',
    name: 'NEO CLASSIC™ 031-A11',
    category: 'neo', categoryLabel: 'Neo Serisi',
    img: '/products/neo/neo-classic-031-a11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Nitril', 'Mavi', 'Genel Kullanım'],
    features: ['Tam Daldırma', 'Pürüzlü Bilek', 'Konfor Astar'],
    specs: { 'EN 388': '4121X', 'Kaplama': 'Nitril', 'Astar': 'Naylon' },
    desc: 'Güçlü nitril kaplaması ve konforlu astarlı yapısıyla inşaat, lojistik ve genel endüstri için ideal eldiven.',
    color: '#1a5c8a',
    usage: ['industrial'], risk: ['low', 'medium'],
  },
  {
    id: 'neo-classic-044-f38',
    name: 'NEO CLASSIC™ 044-F38',
    category: 'neo', categoryLabel: 'Neo Serisi',
    img: '/products/neo/neo-classic-044-f38.jpg',
    material: 'nitrile', length: 'medium',
    tags: ['Turuncu', 'Hi-Viz', 'Endüstriyel'],
    features: ['Yüksek Görünürlük', 'Anti-slip', 'Uzun Pazu'],
    specs: { 'EN 388': '4131X', 'Renk': 'Turuncu', 'Kaplama': 'Nitril köpük', 'Astar': 'Polyester' },
    desc: 'Yüksek görünürlük turuncu rengiyle güvenlik gerektiren ortamlara uygun nitril iş eldiveni.',
    color: '#c94000',
    usage: ['industrial'], risk: ['low', 'medium'],
  },
  {
    id: 'neo-classic-001-p11',
    name: 'NEO CLASSIC™ 001-P11',
    category: 'neo', categoryLabel: 'Neo Serisi',
    img: '/products/neo/neo-classic-001-p11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Siyah', 'Pürüzlü', 'Endüstriyel'],
    features: ['Pürüzlü Avuç', 'Anti-slip', 'Kimyasal Direnç'],
    specs: { 'EN 388': '4131X', 'Renk': 'Siyah', 'Kaplama': 'Nitril', 'Astar': 'Polyester' },
    desc: 'Pürüzlü nitril kaplamasıyla ıslak ve kuru yüzeylerde üstün tutuş sağlayan profesyonel iş eldiveni.',
    color: '#222',
    usage: ['industrial'], risk: ['low', 'medium'],
  },
  {
    id: 'neo-classic-066-d11',
    name: 'NEO CLASSIC™ 066-D11',
    category: 'neo', categoryLabel: 'Neo Serisi',
    img: '/products/neo/neo-classic-066-d11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Gri', 'Hassas İş', 'Çift Kaplama'],
    features: ['Çift Nitril Kaplama', 'Hassas Parmak Ucu', 'Nefes Alabilir Sırt'],
    specs: { 'EN 388': '4131X', 'Renk': 'Gri', 'Kaplama': 'Nitril köpük', 'Astar': 'Naylon/Spandex' },
    desc: 'Çift nitril kaplaması ve nefes alabilen sırt tasarımıyla uzun vardiyalarda maksimum konfor sunar.',
    color: '#555',
    usage: ['industrial'], risk: ['low', 'medium'],
  },
  {
    id: 'neo-lite-001-d11',
    name: 'NEO LITE™ 001-D11',
    category: 'neo', categoryLabel: 'Neo Serisi',
    img: '/products/neo/neo-lite-001-d11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Ultra Hafif', 'Hassas', 'Lite Seri'],
    features: ['Ultra Hafif', 'İnce Nitril Köpük', 'Dokunmatik Uyumlu'],
    specs: { 'EN 388': '4131X', 'Kaplama': 'İnce nitril köpük', 'Astar': 'İnce naylon' },
    desc: 'Neo Lite serisi ultra hafif yapısıyla hassas montaj, elektronik ve kontrol işlemleri için tasarlanmıştır.',
    color: '#1a5c8a',
    usage: ['industrial', 'esd'], risk: ['low'],
  },
  {
    id: 'neo-lite-087-p11',
    name: 'NEO LITE™ 087-P11',
    category: 'neo', categoryLabel: 'Neo Serisi',
    img: '/products/neo/neo-lite-087-p11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Lite', 'Lacivert', 'Genel'],
    features: ['Hafif Yapı', 'Nitril Kaplama', 'Uzun Süre Konfor'],
    specs: { 'EN 388': '4121X', 'Renk': 'Lacivert', 'Kaplama': 'Nitril', 'Astar': 'Polyester' },
    desc: 'Hafif yapısı ve uzun gün konforu ile tercih edilen Neo Lite serisi genel amaçlı iş eldiveni.',
    color: '#1a3a8a',
    usage: ['industrial'], risk: ['low'],
  },
  {
    id: 'neo-lite-ultra-003-p11',
    name: 'NEO LITE ULTRA™ 003-P11',
    category: 'neo', categoryLabel: 'Neo Serisi',
    img: '/products/neo/neo-lite-ultra-003-p11.jpg',
    material: 'nitrile', length: 'short',
    tags: ['Ultra Lite', 'Beyaz', 'Hassas'],
    features: ['Ultra İnce Astar', 'Minimal Ağırlık', 'Hassas İş'],
    specs: { 'EN 388': '4121X', 'Renk': 'Beyaz/Gri', 'Kaplama': 'Nitril köpük', 'Astar': 'Ultra ince naylon' },
    desc: 'Serideki en hafif model. Elektronik montaj, optic ve hassas parça üretimi için optimize edilmiştir.',
    color: '#1a5c8a',
    usage: ['industrial', 'esd'], risk: ['low'],
  },
  {
    id: 'neo-fizz-lite-044-f38',
    name: 'Neo Fizz Lite™ 044-F38',
    category: 'neo', categoryLabel: 'Neo Serisi',
    img: '/products/neo/neo-fizz-lite-044-f38.jpg',
    material: 'nitrile', length: 'medium',
    tags: ['Köpük Kaplama', 'Uzun', 'Konfor'],
    features: ['Fizz Nitril Köpük', 'Uzun Pazu', 'Hava Delikli Sırt'],
    specs: { 'EN 388': '4131X', 'Uzunluk': '380mm', 'Kaplama': 'Fizz nitril köpük', 'Astar': 'Naylon' },
    desc: 'Fizz nitril köpük teknolojisiyle kuru ve ıslak yüzeylerde üstün tutuş, uzun pazu tasarımıyla ek koruma.',
    color: '#c94000',
    usage: ['industrial'], risk: ['low', 'medium'],
  },
  // ── GENEL KULLANIM ────────────────────────────────────────────
  {
    id: 'naturasl-300-11bf',
    name: 'NaturaSL™ 300-11BF',
    category: 'household', categoryLabel: 'Genel Kullanım',
    img: '/products/household/naturasl-300-11bf.png',
    material: 'natural', length: 'short',
    tags: ['Gıda Uyumlu', 'Aloe Vera', 'Ev Tipi'],
    features: ['Doğal Lateks', 'Aloe Vera İçerikli', 'Gıda Sektörüne Uygun', 'Anti-bacterial'],
    specs: { 'Uzunluk': '300mm', 'Renk': 'Kobalt Mavi', 'Astar': 'Pamuk flok', 'Sertifika': 'EN 374' },
    desc: 'Aloe vera katkısıyla cildi besleyen doğal lateks ev eldiveni. Gıda uyumlu yapısıyla mutfak ve temizlik işlemleri için idealdir.',
    color: '#1255a8',
    usage: ['household', 'medical-food'], risk: ['low'],
  },
  // ── TEK KULLANIMLIK ───────────────────────────────────────────
  {
    id: 'lalan-2-8',
    name: 'Lalan™ 2.8',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-2.8.jpg',
    material: 'disposable-nitrile', length: 'disposable',
    tags: ['2.8g', 'Ekonomik', 'Pudrasız'],
    features: ['Pudrasız', 'Lateks İçermez', 'Ambidextrous'],
    specs: { 'Kalınlık': '0.10mm', 'Ağırlık': '2.8g', 'Renk': 'Mavi', 'Paket': '100 adet/kutu' },
    desc: 'Hafif ve ekonomik tek kullanımlık nitril eldiven. Gıda, temizlik ve hafif koruma gerektiren işler için uygundur.',
    color: '#003885',
    usage: ['medical-food', 'household'], risk: ['low'],
  },
  {
    id: 'lalan-lite-3-2',
    name: 'Lalan Lite™ 3.2',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-lite.jpg',
    material: 'disposable-nitrile', length: 'disposable',
    tags: ['Pudrasız', 'Medikal', 'Yüksek Hassasiyet'],
    features: ['Pudrasız', 'Steril Sınıf', 'Tıbbi Muayene Uyumlu', 'Lateks İçermez'],
    specs: { 'Kalınlık': '0.10mm', 'Ağırlık': '3.2g', 'Renk': 'Mavi/Gri', 'Sertifika': 'EN 455' },
    desc: 'Ultra ince nitril yapısıyla tıbbi muayene ve hassas laboratuvar işlemleri için ideal. Pudrasız ve steril sınıf formülasyon.',
    color: '#003885',
    usage: ['medical-food', 'esd'], risk: ['low'],
  },
  {
    id: 'lalan-strong-f',
    name: 'Lalan Strong F™',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-strong-f.jpg',
    material: 'disposable-nitrile', length: 'disposable',
    tags: ['Güçlü', '5g', 'Dayanıklı'],
    features: ['Güçlendirilmiş Nitril', 'Parmak Ucu Pürüzlü', 'Ağır İş'],
    specs: { 'Kalınlık': '0.12mm', 'Ağırlık': '5.0g', 'Renk': 'Mavi', 'Paket': '100 adet/kutu' },
    desc: 'Standart tek kullanımlık eldivenlerden daha kalın nitril duvarıyla güçlü koruma. Temizlik, sanayi ve kimyasal temaslar için uygundur.',
    color: '#00418c',
    usage: ['industrial', 'chemical', 'household'], risk: ['medium'],
  },
  {
    id: 'lalan-strong-x',
    name: 'Lalan Strong X™',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-strong-x.jpg',
    material: 'disposable-nitrile', length: 'disposable',
    tags: ['Extra Güçlü', '6.3g', 'Ağır Hizmet'],
    features: ['Extra Kalın Nitril', 'Pürüzlü Yüzey', 'Uzatılmış Bilek'],
    specs: { 'Kalınlık': '0.15mm', 'Ağırlık': '6.3g', 'Renk': 'Mavi/Siyah', 'Paket': '50 adet/kutu' },
    desc: 'Tek kullanımlık kategorinin en güçlü modeli. Ağır temizlik, kimyasal ve endüstriyel uygulamalar için sektörün en yüksek koruma seviyesi.',
    color: '#00418c',
    usage: ['industrial', 'chemical'], risk: ['medium', 'heavy'],
  },
  {
    id: 'lalan-strong-x-esd',
    name: 'Lalan Strong X ESD™',
    category: 'disposable', categoryLabel: 'Tek Kullanımlık',
    img: '/products/disposable/lalan-strong-x.jpg',
    material: 'disposable-nitrile', length: 'disposable',
    tags: ['ESD', 'Anti-statik', 'Elektronik'],
    features: ['ESD Korumalı', 'Anti-statik', 'Elektronik Sektör', 'Extra Kalın'],
    specs: { 'Kalınlık': '0.15mm', 'ESD': 'IEC 61340-5-1', 'Renk': 'Siyah', 'Paket': '50 adet/kutu' },
    desc: 'ESD (Elektrostatik Deşarj) korumalı formülasyonuyla elektronik üretim ve hassas bileşen montajı için geliştirilmiş özel nitril eldiven.',
    color: '#222',
    usage: ['esd', 'industrial'], risk: ['medium'],
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'Tümü' },
  { id: 'industrial', label: 'Endüstriyel' },
  { id: 'neo', label: 'Neo Serisi' },
  { id: 'household', label: 'Genel Kullanım' },
  { id: 'disposable', label: 'Tek Kullanımlık' },
] as const;
